export const resList = 
 [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "640422",
        name: "Deliure & The Eatrium",
        uuid: "fb2926f8-52e7-4aae-a6e0-656448ac8abe",
        city: "5",
        area: "Thane Panchpakhadi",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "10ee2905f7f3ff8645bacb3797808a2a",
        cuisines: ["Desserts", "Bakery", "Snacks", "Chaat"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "deliure-thane-panchpakhadi-thane-panchpakhadi",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "SHOP NO , GROUND FLOOR GAGANGIRI CHS LTD, PANCHPAKHADI, THANE WEST, THANE - 400601",
        locality: "Thane West",
        parentId: 70641,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7281374~p=1~eid=00000189-21cc-c849-3032-8cfe00040138~srvts=1688489216073",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "640422",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.6",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "25610",
        name: "Balaji Food Court",
        uuid: "f752387f-7752-4938-9666-cbc2c582f6c4",
        city: "5",
        area: "Thane Panchpakhadi",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "mx2xvec1dkyu8yxor1ml",
        cuisines: [
          "North Indian",
          "Chinese",
          "Juices",
          "Continental",
          "Ice Cream",
          "South Indian",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: "39 MINS",
        lastMileTravel: 0.5,
        slugs: {
          restaurant: "balaji-food-court-panch-pakhadi-thane-west-thane",
          city: "mumbai",
        },
        cityState: "5",
        address: "Shop 4 & 5, Sital Premises, Panch Pakhadi, Thane West",
        locality: "Panch Pakhadi",
        parentId: 40639,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "25610",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 0.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "31242",
        name: "The Belgian Waffle Co.",
        uuid: "24094f05-a59c-4611-bef6-ae8ce60a61c3",
        city: "5",
        area: "Panchpakhadi",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "fiigjot2a635empu4eev",
        cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "the-belgian-waffle-co-naupada-thane-west-thane",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop B/4, Monalisa - B, Near Hariniwas Circle, Naupada, Thane West",
        locality: "Naupada, Thane West",
        parentId: 2233,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "31242",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.5",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "26842",
        name: "Vaibhav Chinese Centre",
        uuid: "31196c31-3316-4360-bf06-b5fd60c567d7",
        city: "5",
        area: "Thane Panchpakhadi",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "ocowgzrolqwgcukqcnfk",
        cuisines: ["Chinese", "Oriental", "Beverages", "Pan-Asian"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        slaString: "40 MINS",
        lastMileTravel: 0.699999988079071,
        slugs: {
          restaurant: "vaibhav-chinese-centre-panch-pakhadi-thane-west-thane",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Vaibhav chinese center Sable wadi, Near nitin company signal, Service Road, panchpakhadi, Thane 400602.",
        locality: "Panch Pakhadi",
        parentId: 260010,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7262353~p=4~eid=00000189-21cc-c849-3032-8cff00040440~srvts=1688489216073",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹150 OFF",
          subHeader: "ABOVE ₹299",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "26842",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          lastMileTravel: 0.699999988079071,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "31982",
        name: "Natural Ice Cream",
        uuid: "dd667921-027d-4a0d-8675-eb91174969be",
        city: "5",
        area: "Thane Panchpakhadi",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "rh36c6jr5iaqy3ltq6ht",
        cuisines: ["Ice Cream", "Desserts"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "natural-ice-cream-opposite-hotel-malvan-thane",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "5, Akanksha, Opposite Hotel Malvan, Panch Pakhdi, Thane West, Bhakti Mandir, Panch Pakhdi, Thane West, Mumbai, Maharashtra 400602",
        locality: "Opposite Hotel Malvan",
        parentId: 2093,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "31982",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.7",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "23676",
        name: "McDonald's",
        uuid: "c18ae507-9cb0-4708-b4fc-754a2902222e",
        city: "5",
        area: "Naupada",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
        cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 1.600000023841858,
        slugs: {
          restaurant: "mc-donalds-thane-thane",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "McDonald's Family Restaurant, Gr.Floor,Plot # 23, Wadhavicar Wadi, Bhav Baug, Gokhale Rd, Naupada, Thane (West), Thane - 400 602.",
        locality: "Thane Station",
        parentId: 630,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "23676",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 1.600000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "405325",
        name: "99 Pancakes",
        uuid: "aec55add-e7ee-4d61-a98d-8d00186da9d5",
        city: "5",
        area: "Thane Panchpakhadi",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "c2f533ee4960991a29227a27f516c59b",
        cuisines: ["Ice Cream", "Desserts"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant: "99-pancakes-teen-hath-naka-thane-panchpakhadi",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "SHOP NO.10,GAGANGIRI APT.RAVI COMPOUND PANCH PAKHADI THANE WEST , Naupada Zone, Thane Municipal Corporation (Thane Zone-1), Maharashtra-400602",
        locality: "Teen Hath Naka",
        parentId: 387975,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7288354~p=25~eid=00000189-21cc-c849-3032-8d060004190b~srvts=1688489216073",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "405325",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "347539",
        name: "Sbarro - New York Pizza",
        uuid: "d7f98623-fa74-473d-8eb2-c423388e90cf",
        city: "5",
        area: "Naupada",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "jqhbepyszvqexulgxpkx",
        cuisines: ["Pizzas", "Italian", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        slaString: "35 MINS",
        lastMileTravel: 0.30000001192092896,
        slugs: {
          restaurant:
            "sbarro---new-york-pizza-thane-panchpakhadi-thane-panchpakhadi",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop No.7 Elegance, LBS Road, Teen Haat Naka, near Forest Office, Thane West, Thane Municipal Corporation (Thane Zone-1), Maharashtra   400602",
        locality: "Naupada",
        parentId: 179343,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹599",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "347539",
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          lastMileTravel: 0.30000001192092896,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "391326",
        name: "Bhoir Hotel",
        uuid: "f402d7d1-fad8-4d5b-8aed-3e87542d188e",
        city: "5",
        area: "Thane West",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "ud0lkoslklju9gx5jvfe",
        cuisines: [
          "North Indian",
          "Indian",
          "Tandoor",
          "Chinese",
          "Maharashtrian",
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 0.5,
        slugs: {
          restaurant: "bhoir-hotel-thane-panchpakhadi-thane-panchpakhadi",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Ground Floor, Shop No 03, Sitaram Bhuvan CHS and South of Ma Bhavani CHS, At Bhavani Mata Service Road, Naupada, Thane West-400607",
        locality: "Naupada",
        parentId: 44877,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "391326",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 0.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "695891",
        name: "Brijwasi Sweets, Original Since 1946",
        uuid: "c71d6f56-fa38-4579-a53e-90c9c0214c7f",
        city: "5",
        area: "Blue Nile",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "c3fe7150249b28009707f09d38c038d2",
        cuisines: ["Sweets", "Snacks", "Chaat", "Beverages", "Indian"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 1.399999976158142,
        slugs: {
          restaurant: "brijwasi-sweets,-original-since-1946-dombivli-dombivli",
          city: "mumbai",
        },
        cityState: "5",
        address:
          "Shop No. 6 & 7, Ground Floor, Blue Nile, LBS Marg, Near Vandana Cinema, Thane West",
        locality: "Near Vandana Cinema",
        parentId: 409024,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3500,
          message: "",
          title: "Delivery Charge",
          amount: "3500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7385105~p=10~eid=00000189-21cc-c849-3032-8d0100040a46~srvts=1688489216073",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "695891",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 1.399999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
        },
    {
"type": "restaurant",
"data": {
"type": "F",
"id": "253430",
"name": "Dabba Garam (Homely Meals & More)",
"uuid": "f9dc38cc-ff6f-4342-9fb9-fd4384bbd18a",
"city": "5",
"area": "Thane Panchpakhadi",
"totalRatingsString": "10000+ ratings",
"cloudinaryImageId": "x16a0jf16nz6abrld2vk",
"cuisines": [
"Home Food",
"North Indian",
"Thalis"
],
"tags": [],
"costForTwo": 15000,
"costForTwoString": "₹150 FOR TWO",
"deliveryTime": 32,
"minDeliveryTime": 32,
"maxDeliveryTime": 32,
"slaString": "32 MINS",
"lastMileTravel": 1.2000000476837158,
"slugs": {
"restaurant": "dabba-garam-thane-thane-2",
"city": "mumbai"
},
"cityState": "5",
"address": "Dabba Garam-Naupada, shop no 1, swayam shrushti complex, Chandanwadi, Thane West, Thane, Maharastra-400601",
"locality": "Charai",
"parentId": 67608,
"unserviceable": false,
"veg": true,
"select": false,
"favorite": false,
"tradeCampaignHeaders": [],
"chain": [],
"feeDetails": {
"fees": [
{
"name": "distance",
"fee": 3500,
"message": ""
},
{
"name": "time",
"fee": 0,
"message": ""
},
{
"name": "special",
"fee": 0,
"message": ""
}
],
"totalFees": 3500,
"message": "",
"title": "Delivery Charge",
"amount": "3500",
"icon": ""
},
"availability": {
"opened": true,
"nextOpenMessage": "",
"nextCloseMessage": ""
},
"longDistanceEnabled": 0,
"rainMode": "NONE",
"thirdPartyAddress": false,
"thirdPartyVendor": "",
"adTrackingID": "",
"badges": {
"imageBased": [],
"textBased": [],
"textExtendedBadges": []
},
"lastMileTravelString": "1.2 kms",
"hasSurge": false,
"aggregatedDiscountInfoV3": {
"header": "₹125 OFF",
"subHeader": "ABOVE ₹499",
"discountTag": "FLAT DEAL",
"headerTypeV2": 0
},
"sla": {
"restaurantId": "253430",
"deliveryTime": 32,
"minDeliveryTime": 32,
"maxDeliveryTime": 32,
"lastMileTravel": 1.2000000476837158,
"lastMileDistance": 0,
"serviceability": "SERVICEABLE",
"rainMode": "NONE",
"longDistance": "NOT_LONG_DISTANCE",
"preferentialService": false,
"iconType": "EMPTY"
},
"promoted": false,
"avgRating": "4.3",
"totalRatings": 10000,
"new": false
},
"subtype": "basic"
},{
"type": "restaurant",
"data": {
"type": "F",
"id": "426474",
"name": "Veg Sutra",
"uuid": "898d8b2a-eb3f-4dda-9a7a-b88cfab5292e",
"city": "5",
"area": "Thane Panchpakhadi",
"totalRatingsString": "1000+ ratings",
"cloudinaryImageId": "zcpjz7clwie4tluwk027",
"cuisines": [
"North Indian",
"Chinese",
"Jain"
],
"tags": [],
"costForTwo": 35000,
"costForTwoString": "₹350 FOR TWO",
"deliveryTime": 31,
"minDeliveryTime": 31,
"maxDeliveryTime": 31,
"slaString": "31 MINS",
"lastMileTravel": 0.6000000238418579,
"slugs": {
"restaurant": "veg-sutra-thane-panchpakhadi-thane-panchpakhadi",
"city": "mumbai"
},
"cityState": "5",
"address": "SHOP NO 19, MONALISA, HARI NIWAS, LBS MARG,THANE MUNICIPAL CORPORATION (THANE ZONE-1), MAHARASHTRA -400602",
"locality": "Lbs Marg",
"parentId": 10928,
"unserviceable": false,
"veg": true,
"select": false,
"favorite": false,
"tradeCampaignHeaders": [],
"chain": [],
"feeDetails": {
"fees": [
{
"name": "distance",
"fee": 3500,
"message": ""
},
{
"name": "time",
"fee": 0,
"message": ""
},
{
"name": "special",
"fee": 0,
"message": ""
}
],
"totalFees": 3500,
"message": "",
"title": "Delivery Charge",
"amount": "3500",
"icon": ""
},
"availability": {
"opened": true,
"nextOpenMessage": "",
"nextCloseMessage": ""
},
"longDistanceEnabled": 0,
"rainMode": "NONE",
"thirdPartyAddress": false,
"thirdPartyVendor": "",
"adTrackingID": "",
"badges": {
"imageBased": [],
"textBased": [],
"textExtendedBadges": []
},
"lastMileTravelString": "0.6 kms",
"hasSurge": false,
"aggregatedDiscountInfoV3": {
"header": "30% OFF",
"subHeader": "UPTO ₹75",
"discountTag": "",
"headerTypeV2": 0
},
"sla": {
"restaurantId": "426474",
"deliveryTime": 31,
"minDeliveryTime": 31,
"maxDeliveryTime": 31,
"lastMileTravel": 0.6000000238418579,
"lastMileDistance": 0,
"serviceability": "SERVICEABLE",
"rainMode": "NONE",
"longDistance": "NOT_LONG_DISTANCE",
"preferentialService": false,
"iconType": "EMPTY"
},
"promoted": false,
"avgRating": "4.2",
"totalRatings": 1000,
"new": false
},
"subtype": "basic"
},
  ]


